### ISSUE TITLE
Problems paging lists

### ISSUE THREAD

**Issue by etlund** [bcurren/freshbooks.rb#3]
I can't figure out how to page through lists (like Client.list).  Seems that any thing i try ends up grabbing the entire list instead of just pages.  Any suggestions what I might be doing wrong?

**Comment by bcurren** [comment]
When you iterate through the results it will automatically get the next page behind the scenes. I think this is a nice feature but there are times when you want to deal with pages of day rather than one virtual set. I'll be refactoring this in the near future or grab in a change from the forked repos.
